/* eslint-disable prettier/prettier */
/** Auto-generated by scripts/generateInterviewFaqs.mjs — 100 FAQs */
export type InterviewFaq = { id: number; category: string; question: string; answer: string };

export const INTERVIEW_FAQS: InterviewFaq[] = [
  {
    "id": 1,
    "category": "Data structures — Arrays",
    "question": "What does O(1) random access imply for algorithms using arrays?",
    "answer": "Array indices reach memory in constant time because the element address is base + index × stride. That drives two-pointer scans, sliding windows, and in-place rotates but does not automatically make inserts O(1)."
  },
  {
    "id": 2,
    "category": "Data structures — Arrays",
    "question": "When is a sliding window preferable to nested loops on an array?",
    "answer": "When the optimum for every window can be deduced by adding one element and dropping another in amortized constant time rather than recomputing the whole slice. Typical examples are substring with at most k distinct chars or minimum subarray sums."
  },
  {
    "id": 3,
    "category": "Data structures — Arrays",
    "question": "How do prefix sums accelerate range queries?",
    "answer": "Compute cumulative sums once in O(n) so any sum from i through j resolves as prefix[j]-prefix[i-1]. Trade memory for turning each query into arithmetic instead of iterating the span."
  },
  {
    "id": 4,
    "category": "Linked lists",
    "question": "Why reverse a linked list iteratively versus recursively?",
    "answer": "Iterative reversing uses O(1) auxiliary space besides pointers while naive recursion consumes O(n) stack frames until tail-call optimization is unavailable. Interviewers prefer the iterative three-pointer sketch."
  },
  {
    "id": 5,
    "category": "Linked lists",
    "question": "How detect a cycle without extra hashing?",
    "answer": "Floyd tortoise-and-hare: advance slow one step and fast two steps—meeting proves a cycle; reset one pointer to head and march both one step each to locate the junction."
  },
  {
    "id": 6,
    "category": "Linked lists",
    "question": "Difference between merges on arrays versus linked lists?",
    "answer": "Linked lists splice without shifting elements making merge sort achievable in O(n log n) time with only pointer swaps, unlike array merges that need auxiliary buffers proportional to merges."
  },
  {
    "id": 7,
    "category": "Stacks & queues",
    "question": "What problem pattern maps naturally to monotone stacks?",
    "answer": "Next greater/smaller elements: maintain decreasing stack values and pop while current element exceeds peek, recording answers once relationship known. Complexity stays linear because each item pushes once."
  },
  {
    "id": 8,
    "category": "Stacks & queues",
    "question": "How implement a queue using two stacks?",
    "answer": "Push everything onto inbox stack; dequeue pops from outbox refill by transferring inbox whenever outbox empty—each element moves at most twice amortized giving O(1) amortized dequeue."
  },
  {
    "id": 9,
    "category": "Stacks & queues",
    "question": "Why use deque for sliding window minimum?",
    "answer": "Monotonic deque retains candidate indices sorted by values so shrinking window drops obsolete indices from front while enforcing order from back—each index enqueued/dequeued once."
  },
  {
    "id": 10,
    "category": "Hash tables",
    "question": "Average vs worst-case hashing performance?",
    "answer": "Average O(1) assumes good spread and bounded load factor; adversarial keys can degrade to chains length O(n) unless universal hashing plus resizing mitigates hotspots."
  },
  {
    "id": 11,
    "category": "Hash tables",
    "question": "When does a multiset need a trie instead of a hash map?",
    "answer": "When querying lexicographical neighbors, autocomplete prefixes, or counting shared prefixes dominates point lookups hashed strings cannot traverse incrementally across shared structure."
  },
  {
    "id": 12,
    "category": "Hash tables",
    "question": "Collisions in JS Map objects?",
    "answer": "Modern engines probe or chain internally; interviewer expectation is acknowledging worst-case degrade and guarding with equal hash redistribution when rolling custom buckets."
  },
  {
    "id": 13,
    "category": "Trees — BST basics",
    "question": "Validate BST invariant in one traversal?",
    "answer": "Track allowed min/max window per subtree; left child must lie below parent and above inherited floor, right symmetrical—O(n) time O(h) recursion stack."
  },
  {
    "id": 14,
    "category": "Trees — BST basics",
    "question": "Why augment BST with subtree sizes?",
    "answer": "To answer order-statistics: rank queries need knowing left subtree cardinality before deciding recurse direction and subtracting counted nodes. Rotations update aggregates carefully."
  },
  {
    "id": 15,
    "category": "Trees — BST basics",
    "question": "Balance importance for interview trees?",
    "answer": "Unbalanced BST hits O(n) depth; AVL/red-black guarantee O(log n) height so operations predictable—often abstracted unless rotation details requested."
  },
  {
    "id": 16,
    "category": "Heaps & priority queues",
    "question": "Heapify versus repeated insert?",
    "answer": "Heapify bottoms-up adjusts each subtree in reverse level order yielding O(n) total vs n inserts costing O(n log n); building from array prefers heapify trick."
  },
  {
    "id": 17,
    "category": "Heaps & priority queues",
    "question": "When fractional knapsack needs greedy heap?",
    "answer": "Rarely—you sort items by value/weight ratio once; heaps appear when greedy choices depend on dynamically changing best fronts like merging k sorted arrays."
  },
  {
    "id": 18,
    "category": "Heaps & priority queues",
    "question": "Two heaps median trick?",
    "answer": "Lower half max-heap mirrors upper half min-heap; insert balancing sizes so median always root of larger heap or average of tops when balanced—O(log n)."
  },
  {
    "id": 19,
    "category": "Graph traversal",
    "question": "BFS vs DFS for shortest unweighted paths?",
    "answer": "BFS expands layer by layer preserving minimal edge count whereas DFS explores deep branches first and misses earliest layers unless memoized revisit strategy added."
  },
  {
    "id": 20,
    "category": "Graph traversal",
    "question": "Detect bipartite graph?",
    "answer": "Color start node; neighbors must alternate colors—conflict proves odd cycle; DFS/BFS propagate constraints and run O(V+E)."
  },
  {
    "id": 21,
    "category": "Graph traversal",
    "question": "Topological order prerequisites?",
    "answer": "Only DAGs—run DFS finishing times or indegree peeling; cycles leave nodes with perpetual positive indegree so queue drains early revealing impossibility."
  },
  {
    "id": 22,
    "category": "Dynamic programming patterns",
    "question": "Bottom-up DP vs memoized recursion?",
    "answer": "Bottom-up avoids stack limits and locality benefits; memoized top-down expresses recurrence directly mirroring proofs but risks stack overflow on huge depth despite identical asymptotics."
  },
  {
    "id": 23,
    "category": "Dynamic programming patterns",
    "question": "How spot overlapping subproblems?",
    "answer": "Branches recompute identical parameters—cache keyed by tuples of indices/decisions turns exponential brute force into pseudopolynomial or polynomial memo tables."
  },
  {
    "id": 24,
    "category": "Dynamic programming patterns",
    "question": "Space optimize 1D knapsack?",
    "answer": "Iterate weights descending when reusing single array row so combining item i does not read already-updated dp[w-weight] belonging to same iteration."
  },
  {
    "id": 25,
    "category": "Binary search",
    "question": "Why variants for lower bound versus upper bound?",
    "answer": "Three-pointer partition handles duplicates; invariant keeps answer inside shrinking closed interval distinguishing first ≥ target versus last ≤ target implementations."
  },
  {
    "id": 26,
    "category": "Binary search",
    "question": "Binary search on answer pattern?",
    "answer": "When monotonic predicate over candidate values—check feasibility costing f(mid) amortized separates search space logarithmically despite evaluation sometimes heavy."
  },
  {
    "id": 27,
    "category": "Binary search",
    "question": "Pivot rotated sorted array?",
    "answer": "Shrink interval while nums[lo]<nums[mid] declares left sorted else right—compare target against sorted halves to discard half recursively."
  },
  {
    "id": 28,
    "category": "Sorting & selection",
    "question": "QuickSort average vs guaranteed worst?",
    "answer": "Random pivot amortizes expected O(n log n) but deterministic bad pivots degrade to O(n²); introspective sort switches to heapsort tails in libraries."
  },
  {
    "id": 29,
    "category": "Sorting & selection",
    "question": "When radix sort beats comparison sorts?",
    "answer": "Fixed-width integer keys bounded by alphabet size w—O(n·w) when w small vs comparison lower bound Ω(n log n)."
  },
  {
    "id": 30,
    "category": "Sorting & selection",
    "question": "Median of medians?",
    "answer": "Divide into groups of five, recurse medians, partition—guarantees linear-time selection underpinning deterministic pivot quickselect worst-case proofs."
  },
  {
    "id": 31,
    "category": "System design lite",
    "question": "CAP tradeoff gist?",
    "answer": "During partition can’t simultaneously guarantee consistency and availability; systems pick CP (strong consistency outages) versus AP eventual consistency overlays."
  },
  {
    "id": 32,
    "category": "System design lite",
    "question": "Idempotent POST importance?",
    "answer": "Retries from clients or gateways replay requests; idempotent keys or duplicate detection tables avoid charging twice banking style operations."
  },
  {
    "id": 33,
    "category": "System design lite",
    "question": "Rate limiting strategies?",
    "answer": "Token bucket smoothes bursts leaky bucket smoothes averages; Redis sliding windows approximate distributed fairness with atomic Lua scripts or sorted sets pruning old timestamps."
  },
  {
    "id": 34,
    "category": "Networking & HTTP",
    "question": "Difference PUT vs PATCH semantics?",
    "answer": "PUT replaces entire resource representations client supplies while PATCH conveys partial deltas; naive servers map PATCH poorly so document expectations."
  },
  {
    "id": 35,
    "category": "Networking & HTTP",
    "question": "JWT structure & risks?",
    "answer": "Header.payload.signature; verify signature/expiry server-side never trust client without rotation; stealing tokens equals session hijack prompting httpOnly rotating refresh tokens pair."
  },
  {
    "id": 36,
    "category": "Networking & HTTP",
    "question": "WebSockets vs SSE?",
    "answer": "SSE one-way streaming over HTTP simplicity with auto-reconnect; WebSockets duplex low-latency but stateful infra complexity—pick by directionality/interaction model."
  },
  {
    "id": 37,
    "category": "Databases",
    "question": "Normalization goals?",
    "answer": "Reduce redundancy insertion/update anomalies via functional dependencies—typically to 3NF/Boyce-Codd at cost of joins denormalizing later for analytics."
  },
  {
    "id": 38,
    "category": "Databases",
    "question": "Indexing tradeoffs?",
    "answer": "B-tree indexes accelerate reads/order but slow writes and occupy space; cardinality low columns benefit less selective indexes sometimes composite better."
  },
  {
    "id": 39,
    "category": "Databases",
    "question": "Serializable isolation vs snapshots?",
    "answer": "Serializable prevents phantom reads via predicates locks or SSI anomalies tracking; snapshots allow readers non-blocking albeit stale bounded versions."
  },
  {
    "id": 40,
    "category": "Operating systems",
    "question": "Process versus thread?",
    "answer": "Processes isolate memory maps crash-safe but costly context switches; threads share address space simplifying data sharing risking race hazards requiring synchronization primitives."
  },
  {
    "id": 41,
    "category": "Operating systems",
    "question": " Mutex vs semaphore?",
    "answer": "Mutex binary ownership guarding critical section recursive unsafe unless typed; semaphore counts generalized resources permitting multiple holders without strict ownership concept."
  },
  {
    "id": 42,
    "category": "Operating systems",
    "question": "Virtual memory paging?",
    "answer": "MMUs map virtual to physical frames page faults fetching disk backing store demand paging thrashes if working set exceeds RAM—replacement policies LRU approximations dominate."
  },
  {
    "id": 43,
    "category": "JavaScript / TypeScript",
    "question": "Explain event loop phases briefly?",
    "answer": "Timers poll check microtasks promises before macrotasks; understanding ordering prevents starvation bugs sequencing await versus setImmediate in Node quirks."
  },
  {
    "id": 44,
    "category": "JavaScript / TypeScript",
    "question": "What closures capture?",
    "answer": "Environment records binding outer lexical variables—even after outer function returns—impacting loops using var versus let iterators when scheduling callbacks."
  },
  {
    "id": 45,
    "category": "JavaScript / TypeScript",
    "question": "Structural typing VS nominal?",
    "answer": "TypeScript aligns shapes implicitly unlike Java nominal classes—inference satisfied by duck typing simplifying adapters but weakening brand distinctions unless branded types pattern."
  },
  {
    "id": 46,
    "category": "React",
    "question": "Why concurrent rendering?",
    "answer": "Lets React interrupt rendering for urgent updates yielding smoother UX by time-slicing work without forfeiving correctness guarded by suspense boundaries prioritization."
  },
  {
    "id": 47,
    "category": "React",
    "question": "useEffect cleanup purpose?",
    "answer": "Unsubscribe timers abort controllers preventing memory leaks/state updates post-unmount when dependencies change rerun sequence cleanup-first then setup."
  },
  {
    "id": 48,
    "category": "React",
    "question": "Controlled vs uncontrolled inputs?",
    "answer": "Controlled binds value to React state guaranteeing single source truth validation easy; uncontrolled relies refs/DOM bridging legacy forms migrating gradually."
  },
  {
    "id": 49,
    "category": "Node.js backend",
    "question": "Cluster module benefit?",
    "answer": "Spawns worker processes sharing server port multiplying CPU-bound throughput while isolating faults—mind shared nothing except message passing clustering stateful sessions carefully."
  },
  {
    "id": 50,
    "category": "Node.js backend",
    "question": "Stream backpressure?",
    "answer": "Consumers signal pause/resume aligning producer speed avoiding RAM blowups piping fs read to gzip to network automatically coordinates via highWaterMark thresholds."
  },
  {
    "id": 51,
    "category": "Node.js backend",
    "question": "Graceful shutdown steps?",
    "answer": "Stop accepting sockets drain in-flight finalize DB pools notify orchestrator respecting SIGTERM chaining timeouts kill only if stuck."
  },
  {
    "id": 52,
    "category": "Security basics",
    "question": "CSRF defenses?",
    "answer": "SameSite cookies tighten cross-site embedding plus anti-CSRF synchronizer tokens validating origin headers combos mitigating forged state-changing requests."
  },
  {
    "id": 53,
    "category": "Security basics",
    "question": "Parameterized queries why?",
    "answer": "Bind variables separate SQL structure from literals eliminating injection payloads constructing unintended statements—never interpolate raw inputs."
  },
  {
    "id": 54,
    "category": "Security basics",
    "question": "OAuth vs JWT access tokens?",
    "answer": "OAuth describes authorization delegation flows; bearer JWT often implements access tokens but refresh rotation and audience claims still paramount—don’t confuse protocol with transport."
  },
  {
    "id": 55,
    "category": "Testing & CI",
    "question": "Unit versus integration boundaries?",
    "answer": "Unit isolates deterministic pure modules mocked dependencies fast; integration exercises real collaborators catching wiring failures slower flakiness risk climbs."
  },
  {
    "id": 56,
    "category": "Testing & CI",
    "question": "Deterministic flaky test causes?",
    "answer": "Leaky globals unsynchronized clocks shared mutable singleton race ordering—prefer hermetic sandbox fixtures resetting between tests clocks injection."
  },
  {
    "id": 57,
    "category": "Testing & CI",
    "question": "Smoke versus regression suites?",
    "answer": "Smoke shallow critical path validating deploy viability minutes; regression broad historical bug coverage nightly balancing signal versus duration tradeoffs pipelines."
  },
  {
    "id": 58,
    "category": "Behavioral / STAR",
    "question": "STAR format outline?",
    "answer": "Situation/Task context sets stakes; Action specifics you drove; Results quantify outcomes showing metrics learning loops closing behavioral prompts cleanly."
  },
  {
    "id": 59,
    "category": "Behavioral / STAR",
    "question": "Discussing constructive conflict?",
    "answer": "Emphasize data-driven dissent resolved via prototypes or escalation paths aligning stakeholders—avoid blame articulate compromise outcomes lessons codified afterward."
  },
  {
    "id": 60,
    "category": "Behavioral / STAR",
    "question": "Talking failure authentically?",
    "answer": "Pick substantive miss describe detection mitigation prevention guardrails instituted demonstrating accountability growth—never faux perfection narratives."
  },
  {
    "id": 61,
    "category": "Complexity intuition",
    "question": "Amortized analysis intuition?",
    "answer": "Occasional expensive operations prepaid by cheaper ones averaged over sequence—dynamic array doubling aggregated insertions remain O(1) amortized."
  },
  {
    "id": 62,
    "category": "Complexity intuition",
    "question": "Master theorem quick use?",
    "answer": "Recurrences T(n)=a T(n/b)+f(n)—compare f(n) to n^(log_b a) regimes dominated by roots leaves or balanced driving Θ guesses for divide conquer."
  },
  {
    "id": 63,
    "category": "Complexity intuition",
    "question": "Difference Θ vs O casually stated?",
    "answer": "O upper bound maybe loose; Ω lower; Θ simultaneous tight characterization—mentioning pure O hides best cases interview precision expects Θ clarifications known inputs."
  },
  {
    "id": 64,
    "category": "Strings",
    "question": "Why KMP amortized linear?",
    "answer": "Failure function reuses comparisons skipping redundant retraces guaranteeing pointer on text advances monotonic total O(len)."
  },
  {
    "id": 65,
    "category": "Strings",
    "question": "Rolling hash pitfalls?",
    "answer": "Mod collisions choose double hashing large primes rerun verification substring equality brute confirm—birthday paradox still rare but nondeterministic failure guard."
  },
  {
    "id": 66,
    "category": "Strings",
    "question": "Unicode complexity interviewing?",
    "answer": "Grapheme clusters surpass code points exceed bytes—iteration naive charAt breaks emoji sequences awareness internationalization regressions cropping."
  },
  {
    "id": 67,
    "category": "Bit manipulation",
    "question": "Isolate lowest set bit trick?",
    "answer": "n & -n leverages two complement isolating trailing 1 bitmask useful Fenwick iterating ancestors or counting 1-bits variations."
  },
  {
    "id": 68,
    "category": "Bit manipulation",
    "question": "XOR swap caveats?",
    "answer": "Same memory alias corrupts swapping—also integer overflow misconceptions though XOR bitwise safe commutative reversible only distinct locations."
  },
  {
    "id": 69,
    "category": "Bit manipulation",
    "question": "Bitmask DP state encoding?",
    "answer": "Subsets enumerated as ints width ≤20 typical travel salesman small n—checking membership O(1) toggles via bitwise ops transitions precomputed transitions."
  },
  {
    "id": 70,
    "category": "Probability & hashing",
    "question": "Bloom filters tradeoff?",
    "answer": "Space-efficient memberships with configurable false-positive rate impossible deletions canonical unless counting variant—ideal caches negative lookups CDN edges."
  },
  {
    "id": 71,
    "category": "Probability & hashing",
    "question": "Birthday paradox hashing?",
    "answer": "~√N trials yield collision expectation guiding load factor thresholds rehash resizing birthday bound intuition bucketing churn."
  },
  {
    "id": 72,
    "category": "Probability & hashing",
    "question": "Monte Carlo vs Las Vegas?",
    "answer": "Monte terminates fixed time approximate correctness probability; Las Vegas always correct expected bounded time randomized quicksort pivot randomized expected O(n log n)."
  },
  {
    "id": 73,
    "category": "API design",
    "question": "Version REST APIs?",
    "answer": "Path prefix /v1 stable breaking changes incremented document deprecations sunset headers sparing clients surprise contract tests guard migrations."
  },
  {
    "id": 74,
    "category": "API design",
    "question": "Pagination cursors versus offsets?",
    "answer": "Cursors resilient live mutating datasets avoid skipped duplicatesOffsets cheap static datasets simplistic—choose stability requirements first."
  },
  {
    "id": 75,
    "category": "API design",
    "question": "Hypermedia tradeoffs?",
    "answer": "HATEOAS embeds transitions discoverability improving evolvability but payloads heavier clients cache unfriendly pragmatic hybrids common."
  },
  {
    "id": 76,
    "category": "Caching",
    "question": "Cache stampedes mitigation?",
    "answer": "Probabilistic early expiration stagger recompute TTL jitter locks singleflight consolidating thundering herds backend spikes."
  },
  {
    "id": 77,
    "category": "Caching",
    "question": "CDN cache invalidation strategies?",
    "answer": "Versioned filenames immutable content long TTL versus purge APIs tagging surrogate keys selective bust—choose consistency vs freshness product tolerances."
  },
  {
    "id": 78,
    "category": "Caching",
    "question": "Memoization pitfalls React?",
    "answer": "Referential instability dependencies cause redundant recalcs—memoize selectors with shallow compare aware concurrent rendering tearing stale closures."
  },
  {
    "id": 79,
    "category": "Leadership & collaboration",
    "question": "Prioritizing tech debt?",
    "answer": "Frame impact/risk matrix quantifying incident frequency customer pain pairing incremental repayment SLAs aligning product increments transparently stakeholder trust."
  },
  {
    "id": 80,
    "category": "Leadership & collaboration",
    "question": "Giving code review feedback?",
    "answer": "Ask clarifying assume good intent categorize blocking vs nit label severity pair suggestions rationale reference style guides escalate patterns not individuals."
  },
  {
    "id": 81,
    "category": "Leadership & collaboration",
    "question": "Remote async communication?",
    "answer": "Document decisions searchable durable threads summaries decision logs reduce meetings bias written clarity aligns time zones politely."
  },
  {
    "id": 82,
    "category": "Quality & craftsmanship",
    "question": "Defensive programming?",
    "answer": "Validate boundaries early fail fast assertions logging contexts returning typed errors simplifying caller reasoning secure defaults least privilege layering."
  },
  {
    "id": 83,
    "category": "Quality & craftsmanship",
    "question": "Linting/formatting rationale?",
    "answer": "Uniform diffs shrinking review noise automate bikeshed debates integrate pre-commit hooks CI enforcing zero-warning baselines creeping debt."
  },
  {
    "id": 84,
    "category": "Quality & craftsmanship",
    "question": "Monitoring golden signals?",
    "answer": "Latency traffic errors saturation underpin SLO thinking exemplified Google SRE pairing dashboards alerting actionable runbooks not vanity metrics alone."
  },
  {
    "id": 85,
    "category": "Misc algorithms",
    "question": "Dijkstra non-negative caveat?",
    "answer": "Negative edges break greedy relaxation order requiring Bellman-Ford or Johnson reweighting preprocessing—mention usage boundaries interviews."
  },
  {
    "id": 86,
    "category": "Misc algorithms",
    "question": "Union-find optimizations?",
    "answer": "Path compression union by rank amortized inverse Ackermann nearly constant practical connectivity Kruskal mst leverages ascending edge sort plus DSU merges."
  },
  {
    "id": 87,
    "category": "Misc algorithms",
    "question": "A* versus Dijkstra?",
    "answer": "Heuristic guides search goal-directed admissible heuristics preserve optimality inflate inadmissible speeds approximate navigation games maps."
  },
  {
    "id": 88,
    "category": "Edge cases mindset",
    "question": "Empty input handling?",
    "answer": "Zero-one element arrays often explode divide conquer recurrences—establish base cases proactively tests codifying regressions guarding off-by-one."
  },
  {
    "id": 89,
    "category": "Edge cases mindset",
    "question": "Integer overflow awareness?",
    "answer": "Languages silent wrap—promote long check before multiply addition competitive programming templates pattern multiply safe using bigger types modular tricks."
  },
  {
    "id": 90,
    "category": "Edge cases mindset",
    "question": "Floating accuracy issues?",
    "answer": "Equality unreliable tolerances eps comparisons financial decimal libraries avoid binary float artifacts aggregations currency."
  },
  {
    "id": 91,
    "category": "Async patterns",
    "question": "Promise.all vs allSettled?",
    "answer": "all short-circuits first rejection; allSettled collects outcomes resilience partial success fan-out fan-in aggregations mix strategies."
  },
  {
    "id": 92,
    "category": "Async patterns",
    "question": "Backpressure async iterators?",
    "answer": "for await respecting consumer speed pause upstream observables analogous streaming—uncoordinated buffering risks memory exhaustion asynchronous pipelines engineering."
  },
  {
    "id": 93,
    "category": "Async patterns",
    "question": "Race cancellation?",
    "answer": "AbortController revoke fetch ReadableStream teardown cooperative cancellation patterns preventing zombie updates after navigations UX polish."
  },
  {
    "id": 94,
    "category": "Product thinking",
    "question": "MVP slicing question?",
    "answer": "Identify smallest differentiable value hypothesis metrics proving demand before layering robustness aligning engineering bets validated learning minimizing waste."
  },
  {
    "id": 95,
    "category": "Product thinking",
    "question": "Technical debt communication?",
    "answer": "Translate interest metaphor quantify drag velocity incidents frequency securing dedicated bandwidth negotiation reframing preventive maintenance ally not adversary PM."
  },
  {
    "id": 96,
    "category": "Product thinking",
    "question": "Instrumentation before optimization?",
    "answer": "Profile representative workloads measure hotspots quantify improvements counter intuition premature micro optimizations hurting readability without evidence."
  },
  {
    "id": 97,
    "category": "Distributed basics",
    "question": "Exactly-once semantics reality?",
    "answer": "True exactly-once impossible across networks—idempotent sinks plus at-least-once delivery dedup approximate practical Kafka transactions caveats educating stakeholders."
  },
  {
    "id": 98,
    "category": "Distributed basics",
    "question": "Vector clocks purpose?",
    "answer": "Capture partial ordering events replicas resolving conflicts CRDTs alternative families automatic merge choosing domain-specific resolution policies."
  },
  {
    "id": 99,
    "category": "Distributed basics",
    "question": "Split brain mitigation?",
    "answer": "Quorum majorities fencing tokens prevent stale primaries writing storage epoch negotiation dynamic cluster membership consensus raft/paxos families."
  },
  {
    "id": 100,
    "category": "Mobile / web perf",
    "question": "Critical rendering path?",
    "answer": "Minimize blocking CSS/JS leverage preload preconnect responsive images priority hints improving LCP CLS metrics user perceived performance budgets."
  }
];
